// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Admin struct {
	Seq   uint64         `json:"seq"`
	ID    string         `json:"id"`
	Name  sql.NullString `json:"name"`
	Pw    sql.NullString `json:"pw"`
	Phone sql.NullString `json:"phone"`
}

type Product struct {
	Seq         int64          `json:"seq"`
	Category    sql.NullString `json:"category"`
	Price       int32          `json:"price"`
	Cost        int32          `json:"cost"`
	Name        string         `json:"name"`
	NameInitial string         `json:"name_initial"`
	Description string         `json:"description"`
	Barcode     []byte         `json:"barcode"`
	Expire      time.Time      `json:"expire"`
	Size        int32          `json:"size"`
}
