// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAdmin(ctx context.Context, arg CreateAdminParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	DeleteProduct(ctx context.Context, seq int64) error
	GetAdmin(ctx context.Context, arg GetAdminParams) (*Admin, error)
	GetProduct(ctx context.Context, seq int64) (*Product, error)
	ListProductsByName(ctx context.Context, arg ListProductsByNameParams) ([]*Product, error)
	ListProductsByNameInitial(ctx context.Context, arg ListProductsByNameInitialParams) ([]*Product, error)
	UpdateAdminPw(ctx context.Context, arg UpdateAdminPwParams) error
	UpdateProductIfNotNil(ctx context.Context, arg UpdateProductIfNotNilParams) error
}

var _ Querier = (*Queries)(nil)
